version: '1.0.0.{build}-alpha-{branch}'

configuration: Release

skip_tags: true

platform:
- x86
- x64

matrix:
  fast_finish: true

build:
  verbosity: normal

after_build:
- 7z a %APPVEYOR_PROJECT_NAME%-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\TestCOMServer\TestCOMServer\bin\*\%CONFIGURATION%\*

artifacts:
- path: '**\bin\**\*.dll'
  name: dll
- path: '**\bin\**\*.tlb'
  name: tlb
- path: '\*.zip'
  name: zip

